name: Deploy Contract
on:
  workflow_dispatch:   # manual button

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Deploy to Base
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          RPC_URL: https://base-mainnet.g.alchemy.com/v2/c9sgWYXHHHwxgwSSDwR6gP8PWB5MuTQ0
        run: |
          forge build
          forge create --rpc-url "$RPC_URL" \
                       --private-key "$PRIVATE_KEY" \
                       contracts/ArbitrageFlashloan.sol:ArbitrageFlashloan
